services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper-local
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka-local
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CREATE_TOPICS: "member:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - ./../volumes/kafka:/var/run/docker.sock
    depends_on:
      - zookeeper
